import type { StudentDashboard, ErrorBankEntry, TeacherStudent, TeacherLesson } from '@/types'

export const mockDashboard: StudentDashboard = {
  programProgress: { currentWeek: 7, totalWeeks: 24 },
  currentUnit: {
    id: 'unit-7',
    program_id: 'prog-1',
    week_number: 7,
    theme: 'Reuniões de trabalho',
    vocabulary: [
      'agenda', 'attendee', 'minutes', 'follow-up', 'action item',
      'defer', 'consensus', 'stakeholder', 'takeaway', 'adjourn',
      'brainstorm', 'bottleneck', 'deliverable', 'bandwidth', 'synergy',
      'facilitate', 'alignment', 'scope', 'timeline',
    ],
    expressions: [
      "Let's get started", "Any objections?", "To circle back on that",
      "Moving forward", "Let's table that for now", "Does everyone agree?",
      "Just to recap", "Action item for you",
    ],
    grammar_focus: 'Present Perfect para relatar resultados',
    grammar_explanation:
      'O Present Perfect conecta o passado ao presente. Use-o para falar sobre o que foi feito/decidido: "We have finalized the agenda." vs Simple Past para momento específico: "We finalized it yesterday."',
    can_do_statements: [
      'Consigo conduzir uma reunião de trabalho básica em inglês',
      'Consigo resumir decisões e action items',
      'Consigo usar o Present Perfect para reportar resultados',
    ],
    pre_lesson_text:
      'Business meetings in English follow a clear structure. The facilitator sets the agenda, attendees discuss each item, and the team agrees on action items before adjourning...',
    pre_lesson_audio_url: 'https://example.com/audio/week7.mp3',
    pre_lesson_questions: [
      'What makes a meeting effective?',
      'How do you handle disagreements in meetings?',
      'What follow-up actions do you usually take after a meeting?',
    ],
    pre_lesson_task: 'Escreva 5 frases usando o vocabulário da semana sobre uma reunião que você participou recentemente.',
    lesson_objectives: [
      'Praticar abertura e condução de reuniões',
      'Usar Present Perfect para relatar progresso',
      'Consolidar vocabulário de reuniões em simulação real',
    ],
    post_lesson_task: {
      type: 'audio',
      instruction: 'Grave 1 minuto conduzindo uma reunião fictícia: apresente a pauta, discuta um ponto e encerre com action items.',
      due_days: 5,
    },
    available_from: '2026-06-09T08:00:00Z',
    status: 'active',
  },
  upcomingLesson: {
    id: 'lesson-14',
    student_id: 'student-1',
    teacher_id: 'teacher-1',
    unit_id: 'unit-7',
    scheduled_at: '2026-06-19T22:30:00Z',
    duration_min: 60,
    meet_url: 'https://meet.google.com/abc-defg-hij',
    status: 'scheduled',
    teacher: { full_name: 'Ana Lima', avatar_url: undefined },
  },
  pendingTasks: [
    {
      id: 'task-prev',
      unit_id: 'unit-6',
      student_id: 'student-1',
      type: 'audio',
      instruction: 'Grave 1 minuto apresentando sua empresa para um cliente internacional.',
      due_at: '2026-06-14T23:59:00Z',
      status: 'late',
    },
    {
      id: 'task-pre',
      unit_id: 'unit-7',
      student_id: 'student-1',
      type: 'text',
      instruction: 'Escreva 5 frases usando o vocabulário da semana sobre uma reunião recente.',
      due_at: '2026-06-19T23:59:00Z',
      status: 'pending',
    },
  ],
  engagementScore: 78,
  vocabularyTotal: 134,
  streak: 5,
  pendingVocabReviews: [
    { id: 'v1', word: 'stakeholder', translation: 'parte interessada', due_at: '2026-06-15T08:00:00Z' },
    { id: 'v2', word: 'deliverable', translation: 'entregável', due_at: '2026-06-15T08:00:00Z' },
    { id: 'v3', word: 'bottleneck', translation: 'gargalo', due_at: '2026-06-15T08:00:00Z' },
    { id: 'v4', word: 'adjourn', translation: 'encerrar a reunião', due_at: '2026-06-15T08:00:00Z' },
    { id: 'v5', word: 'consensus', translation: 'consenso', due_at: '2026-06-15T08:00:00Z' },
  ],
}

export const mockPreLessonStatus = {
  vocabularyViewed: true,
  textViewed: true,
  audioViewed: false,
  preLessonTaskDone: false,
}

export const mockUser = {
  id: 'student-1',
  full_name: 'João Silva',
  email: 'joao@email.com',
  role: 'student' as const,
  current_level: 'B1' as const,
  target_level: 'B2' as const,
}

// ─── Error Bank ──────────────────────────────────────────────────
export const mockErrors: ErrorBankEntry[] = [
  {
    id: 'e1',
    student_id: 'student-1',
    category: 'grammar',
    description: 'Usa Simple Past onde deveria usar Present Perfect',
    example: 'I already finished the report.',
    correction: 'I have already finished the report.',
    occurrences: 5,
    status: 'active',
    source: 'teacher',
  },
  {
    id: 'e2',
    student_id: 'student-1',
    category: 'grammar',
    description: 'Omite o auxiliar "do/does" em perguntas',
    example: 'You work on weekends?',
    correction: 'Do you work on weekends?',
    occurrences: 3,
    status: 'active',
    source: 'teacher',
  },
  {
    id: 'e3',
    student_id: 'student-1',
    category: 'vocabulary',
    description: 'Confunde "make" e "do" em expressões fixas',
    example: 'I need to do a decision.',
    correction: 'I need to make a decision.',
    occurrences: 4,
    status: 'improving',
    source: 'teacher',
  },
  {
    id: 'e4',
    student_id: 'student-1',
    category: 'fluency',
    description: 'Pausa excessiva antes de conectivos (however, therefore)',
    example: '—',
    correction: 'Praticar transições: "However, ...", "Therefore, ..."',
    occurrences: 2,
    status: 'active',
    source: 'ai',
  },
  {
    id: 'e5',
    student_id: 'student-1',
    category: 'pronunciation',
    description: 'Pronúncia de "th" como "d" ou "f"',
    example: '"dey" ou "fey" para "they"',
    correction: '"they", "think", "through" — língua entre os dentes',
    occurrences: 6,
    status: 'active',
    source: 'teacher',
  },
  {
    id: 'e6',
    student_id: 'student-1',
    category: 'structure',
    description: 'Ordem de adjetivos incorreta antes do substantivo',
    example: 'A Italian small company',
    correction: 'A small Italian company',
    occurrences: 2,
    status: 'improving',
    source: 'ai',
  },
  {
    id: 'e7',
    student_id: 'student-1',
    category: 'grammar',
    description: 'Uso incorreto de "since" vs "for"',
    example: 'I work here since 3 years.',
    correction: 'I have worked here for 3 years.',
    occurrences: 2,
    status: 'resolved',
    source: 'teacher',
  },
]

// ─── Progress snapshots ──────────────────────────────────────────
export const mockSnapshots = [
  {
    month: 'Jan', speaking: 42, listening: 50, reading: 55, writing: 38, uol: 44,
    lessons: 6, tasks: 5, ai_sessions: 8, vocab: 48,
  },
  {
    month: 'Fev', speaking: 47, listening: 54, reading: 58, writing: 43, uol: 48,
    lessons: 7, tasks: 6, ai_sessions: 11, vocab: 72,
  },
  {
    month: 'Mar', speaking: 52, listening: 60, reading: 63, writing: 49, uol: 53,
    lessons: 8, tasks: 7, ai_sessions: 14, vocab: 98,
  },
  {
    month: 'Abr', speaking: 58, listening: 64, reading: 67, writing: 54, uol: 58,
    lessons: 8, tasks: 8, ai_sessions: 12, vocab: 112,
  },
  {
    month: 'Mai', speaking: 62, listening: 68, reading: 71, writing: 59, uol: 63,
    lessons: 9, tasks: 7, ai_sessions: 16, vocab: 124,
  },
  {
    month: 'Jun', speaking: 66, listening: 72, reading: 74, writing: 63, uol: 67,
    lessons: 5, tasks: 4, ai_sessions: 9, vocab: 134,
  },
]

export const mockCurrentScores = {
  speaking: 66, listening: 72, reading: 74, writing: 63, uol: 67,
}

// ─── AI Chat mock ────────────────────────────────────────────────
export const mockAiMessages = [
  {
    role: 'assistant' as const,
    content: "Hello, João! Let's practice the vocabulary from this week's theme — **Business Meetings**. I'll present each word in context and then ask you to use it in a sentence. Ready?\n\nFirst word: **agenda** — a list of topics to be discussed in a meeting.\n\n*Example: \"Let's review the agenda before we begin.\"*\n\nNow you try: use **agenda** in a sentence related to your work.",
  },
  {
    role: 'user' as const,
    content: 'The manager sent the agenda for tomorrow meeting.',
  },
  {
    role: 'assistant' as const,
    content: "Good attempt! Small correction:\n\n❌ *\"the agenda for tomorrow meeting\"*\n✅ **\"the agenda for tomorrow's meeting\"** (possessive — use apostrophe + s)\n\nYour corrected sentence: *\"The manager sent the agenda for tomorrow's meeting.\"* — \n\nNext word: **stakeholder** — a person or group with an interest in a project or business.\n\n*Example: \"We need to align all stakeholders before the product launch.\"*\n\nYour turn!",
  },
]

// ─── Portfolio ───────────────────────────────────────────────────
export const mockPortfolio = [
  {
    id: 'p1',
    type: 'before_audio' as const,
    title: 'Áudio inicial — Semana 1',
    semester: 1,
    unit_week: 1,
    theme: 'Apresentação pessoal',
    created_at: '2026-01-06T10:00:00Z',
    duration: '1:47',
    transcription: 'Hello, my name is João. I work in technology. I like... em... my job is... developer. I study english because I need for work.',
    score: null,
  },
  {
    id: 'p2',
    type: 'text' as const,
    title: 'E-mail profissional — Semana 3',
    semester: 1,
    unit_week: 3,
    theme: 'Comunicação escrita',
    created_at: '2026-01-20T10:00:00Z',
    duration: null,
    transcription: 'Dear Mr. Johnson, I am writing to follow up on our meeting last week. As we discussed, the project timeline needs to be adjusted...',
    score: 74,
  },
  {
    id: 'p3',
    type: 'after_audio' as const,
    title: 'Áudio semana 6 — Reuniões',
    semester: 1,
    unit_week: 6,
    theme: 'Apresentações profissionais',
    created_at: '2026-02-10T10:00:00Z',
    duration: '2:12',
    transcription: "Good morning everyone. I'd like to start by reviewing our agenda for today's meeting. We have three main points to cover: the Q1 results, our product roadmap for the next quarter, and the budget allocation.",
    score: 81,
  },
  {
    id: 'p4',
    type: 'audio' as const,
    title: 'Simulação de entrevista — Semana 5',
    semester: 1,
    unit_week: 5,
    theme: 'Entrevista de emprego',
    created_at: '2026-02-03T10:00:00Z',
    duration: '3:05',
    transcription: "I've been working as a software developer for five years. In my current role, I'm responsible for leading a team of four engineers. I think my biggest strength is my ability to communicate technical concepts to non-technical stakeholders.",
    score: 78,
  },
]

// ─── Admin mock data ─────────────────────────────────────────────

export const mockAdminMetrics = {
  totalStudents: 142,
  totalTeachers: 8,
  totalGroups: 11,
  activeSubscriptions: 127,
  trialUsers: 15,
  churnedThisMonth: 4,
  revenueMonthly: 38400,
  revenueGrowth: 12,
  avgEngagement: 71,
  aiSessionsToday: 89,
  lessonsToday: 23,
  pendingReports: 5,
}

export const mockAdminUsers = [
  { id: 'student-1', full_name: 'João Silva',      email: 'joao@email.com',     role: 'student'  as const, status: 'active'  as const, plan: 'standard',  teacher: 'Ana Lima',    created_at: '2026-01-06', level: 'B1', language: 'english' },
  { id: 'student-2', full_name: 'Maria Santos',    email: 'maria@email.com',    role: 'student'  as const, status: 'active'  as const, plan: 'standard',  teacher: 'Ana Lima',    created_at: '2026-01-10', level: 'A2', language: 'english' },
  { id: 'student-3', full_name: 'Carlos Ferreira', email: 'carlos@email.com',   role: 'student'  as const, status: 'active'  as const, plan: 'intensive', teacher: 'Ana Lima',    created_at: '2026-01-15', level: 'B2', language: 'english' },
  { id: 'student-4', full_name: 'Patricia Oliveira',email: 'patricia@email.com',role: 'student'  as const, status: 'at_risk' as const, plan: 'light',     teacher: 'Ana Lima',    created_at: '2026-02-01', level: 'A1', language: 'english' },
  { id: 'student-5', full_name: 'Ricardo Costa',   email: 'ricardo@email.com',  role: 'student'  as const, status: 'active'  as const, plan: 'standard',  teacher: 'Ana Lima',    created_at: '2026-02-10', level: 'B1', language: 'english' },
  { id: 'teacher-1', full_name: 'Ana Lima',        email: 'ana@learnix.com',    role: 'teacher'  as const, status: 'active'  as const, plan: '—',         teacher: '—',           created_at: '2025-09-01', level: '—',  language: 'english' },
  { id: 'teacher-2', full_name: 'Bruno Melo',      email: 'bruno@learnix.com',  role: 'teacher'  as const, status: 'active'  as const, plan: '—',         teacher: '—',           created_at: '2025-10-01', level: '—',  language: 'english' },
  { id: 'admin-1',   full_name: 'Learnix Admin',   email: 'admin@learnix.com',  role: 'admin'    as const, status: 'active'  as const, plan: '—',         teacher: '—',           created_at: '2025-01-01', level: '—',  language: '—'      },
]

export const mockAdminTeachers = [
  {
    id: 'teacher-1', full_name: 'Ana Lima', email: 'ana@learnix.com',
    students_count: 5, lessons_this_month: 22, pending_reports: 1,
    avg_student_engagement: 71, specialties: ['Business', 'Exam Prep'],
    is_available: true,
  },
  {
    id: 'teacher-2', full_name: 'Bruno Melo', email: 'bruno@learnix.com',
    students_count: 7, lessons_this_month: 31, pending_reports: 0,
    avg_student_engagement: 78, specialties: ['Beginners', 'Conversação'],
    is_available: true,
  },
  {
    id: 'teacher-3', full_name: 'Carla Dias', email: 'carla@learnix.com',
    students_count: 4, lessons_this_month: 18, pending_reports: 2,
    avg_student_engagement: 65, specialties: ['Espanhol', 'DELE'],
    is_available: false,
  },
]

// ─── Teacher mock data ───────────────────────────────────────────

export const mockTeacher = {
  id: 'teacher-1',
  full_name: 'Ana Lima',
  email: 'ana@learnix.com',
  role: 'teacher' as const,
  specialties: ['Business English', 'Exam Prep', 'Beginners'],
  students_count: 5,
  lessons_today: 2,
  pending_reports: 1,
}

export const mockTeacherStudents: TeacherStudent[] = [
  {
    id: 'student-1',
    full_name: 'João Silva',
    language: 'english',
    current_level: 'B1',
    target_level: 'B2',
    professional_area: 'Tecnologia',
    plan_type: 'standard',
    engagement_score: 78,
    streak: 5,
    vocabulary_total: 134,
    status: 'on_track',
    current_week: 7,
    total_weeks: 24,
    current_theme: 'Reuniões de trabalho',
    pre_lesson_done: false,
    task_pending: true,
    last_lesson_at: '2026-06-12T19:30:00Z',
    next_lesson_at: '2026-06-19T19:30:00Z',
    next_lesson_id: 'lesson-14',
    ai_sessions_week: 3,
    errors_active: 4,
    scores: { speaking: 66, listening: 72, reading: 74, writing: 63, uol: 67 },
  },
  {
    id: 'student-2',
    full_name: 'Maria Santos',
    language: 'english',
    current_level: 'A2',
    target_level: 'B1',
    professional_area: 'Marketing',
    plan_type: 'standard',
    engagement_score: 62,
    streak: 2,
    vocabulary_total: 87,
    status: 'on_track',
    current_week: 5,
    total_weeks: 24,
    current_theme: 'Apresentações profissionais',
    pre_lesson_done: true,
    task_pending: false,
    last_lesson_at: '2026-06-11T17:00:00Z',
    next_lesson_at: '2026-06-16T17:00:00Z',
    next_lesson_id: 'lesson-15',
    ai_sessions_week: 1,
    errors_active: 6,
    scores: { speaking: 48, listening: 55, reading: 60, writing: 44, uol: 51 },
  },
  {
    id: 'student-3',
    full_name: 'Carlos Ferreira',
    language: 'english',
    current_level: 'B2',
    target_level: 'C1',
    professional_area: 'Finanças',
    plan_type: 'intensive',
    engagement_score: 91,
    streak: 14,
    vocabulary_total: 218,
    status: 'on_track',
    current_week: 12,
    total_weeks: 24,
    current_theme: 'Negociação e contratos',
    pre_lesson_done: true,
    task_pending: false,
    last_lesson_at: '2026-06-13T08:00:00Z',
    next_lesson_at: '2026-06-20T08:00:00Z',
    next_lesson_id: 'lesson-16',
    ai_sessions_week: 5,
    errors_active: 2,
    scores: { speaking: 78, listening: 82, reading: 85, writing: 74, uol: 79 },
  },
  {
    id: 'student-4',
    full_name: 'Patricia Oliveira',
    language: 'english',
    current_level: 'A1',
    target_level: 'A2',
    professional_area: 'Saúde',
    plan_type: 'light',
    engagement_score: 32,
    streak: 0,
    vocabulary_total: 41,
    status: 'at_risk',
    current_week: 3,
    total_weeks: 12,
    current_theme: 'Rotina diária',
    pre_lesson_done: false,
    task_pending: true,
    last_lesson_at: '2026-05-29T20:00:00Z',
    next_lesson_at: undefined,
    next_lesson_id: undefined,
    ai_sessions_week: 0,
    errors_active: 8,
    scores: { speaking: 22, listening: 28, reading: 31, writing: 18, uol: 25 },
  },
  {
    id: 'student-5',
    full_name: 'Ricardo Costa',
    language: 'english',
    current_level: 'B1',
    target_level: 'B2',
    professional_area: 'Engenharia',
    plan_type: 'standard',
    engagement_score: 55,
    streak: 1,
    vocabulary_total: 112,
    status: 'on_track',
    current_week: 9,
    total_weeks: 24,
    current_theme: 'Apresentações técnicas',
    pre_lesson_done: true,
    task_pending: false,
    last_lesson_at: '2026-06-10T21:00:00Z',
    next_lesson_at: '2026-06-15T21:00:00Z',
    next_lesson_id: 'lesson-17',
    ai_sessions_week: 2,
    errors_active: 3,
    scores: { speaking: 58, listening: 62, reading: 65, writing: 53, uol: 57 },
  },
]

export const mockTodayLessons: TeacherLesson[] = [
  {
    id: 'lesson-17',
    student: { id: 'student-5', full_name: 'Ricardo Costa', current_level: 'B1' },
    unit: {
      week_number: 9,
      theme: 'Apresentações técnicas',
      grammar_focus: 'Modal verbs para recomendações',
      vocabulary: ['slide', 'outline', 'highlight', 'data', 'trend', 'insight', 'Q&A', 'handout'],
    },
    scheduled_at: '2026-06-15T21:00:00Z',
    duration_min: 60,
    meet_url: 'https://meet.google.com/rco-tech-eng',
    status: 'scheduled',
    pre_lesson_status: { vocabulary_viewed: true, text_viewed: true, audio_viewed: false, task_done: true },
    ai_sessions_week: 2,
    errors_active: 3,
    last_lesson_note: 'Dificuldade com conditionals. Preparar mais exemplos com situações reais de trabalho.',
    report_pending: false,
  },
]

export const mockPendingReportLessons: TeacherLesson[] = [
  {
    id: 'lesson-14',
    student: { id: 'student-1', full_name: 'João Silva', current_level: 'B1' },
    unit: {
      week_number: 6,
      theme: 'Negociação de propostas',
      grammar_focus: 'Conditionals para negociação',
      vocabulary: ['proposal', 'counter-offer', 'negotiate', 'terms', 'agreement', 'compromise'],
    },
    scheduled_at: '2026-06-12T19:30:00Z',
    duration_min: 60,
    meet_url: 'https://meet.google.com/abc-defg-hij',
    status: 'completed',
    pre_lesson_status: { vocabulary_viewed: true, text_viewed: true, audio_viewed: true, task_done: true },
    ai_sessions_week: 3,
    errors_active: 4,
    last_lesson_note: 'Present Perfect ainda confuso. Focou bem em vocabulário de negociação.',
    report_pending: true,
  },
]
